### ISSUE TITLE
No longer available from pip

### ISSUE THREAD

**Issue by voidplayer** [bluebird75/winpdb#12]
```
$ python -m pip install winpdb-reborn
Collecting winpdb-reborn
  Could not find a version that satisfies the requirement winpdb-reborn (from versions: )
No matching distribution found for winpdb-reborn
```

install instructions no longer work

**Comment by bluebird75** [comment]
Good point. I have released a package for Python 2.6 and 2.7 which works with pip.

I will work on an experimental build for Python 3 soon

**Comment by voidplayer** [comment]
Thanks!

I tried and it seems to work

Im really looking forward for the best python debugger gui there was... reborn!

**Comment by voidplayer** [comment]
Actually, the namespace is empty :(

![selection_007](https://user-images.githubusercontent.com/4019910/38220137-fabf4098-36d8-11e8-8fab-6ee1d2796fce.png)

**Comment by voidplayer** [comment]
Im almost sure I was debugging a python2 program

Anyway, im using old winpdb because it still works for my use cases, but i was really happy when i saw somebody picked up the development, because this is the only python debugger which shows every variable in every context by default

I was worried because the last update in the old pdb was really ancient

This bug was about the installation instructions and can be closed if you are aware already of the problem

I will help testing the new releases!
