### ISSUE TITLE
Incompatibilities with wxpython 4.0.7

### ISSUE THREAD

**Issue by UEWiebelitz** [bluebird75/winpdb#33]
It seems that the current git head is not compatible to the wxpython 4.0.7 version.
**Description:** When attaching to a remote session the debugger works find but all control buttons and inspection areas stay disabled. The shortcuts (e.g. F6/F5 work just fine).
This leads to exceptions.

**Reason:** At least the current version of wxPython (4.1.0 and 4.0.7) do not have the type rectS and the type rect does not provide any function inside(). 
These functions are called as wx.rectS(...) and r.inside(...) in winpdb.py.

**Solution:** Replacing wx.rectS by wx.rect and r.inside by r.contains(...) solves the bug and remote debugging works like a charm ;-)

Unfortunately I am not familiar with wxWidgets. Thus I do not know wheter any version ever supported these statements and if so since when this has changed.

If the fix is needed as a patch, please let me know.

**Comment by bluebird75** [comment]
Thanks for finding out. I was wondering why the interface was so empty !

Conversion to WxPython 4 is still an ongoing process, and is more or less stalled at my end. 

Please submit a PR, this will greatly help. And don't hesitate to fix other bugs if you see any !

**Comment by UEWiebelitz** [comment]
I will do it with pleasure but I need a little help:
Do I have to fork the project first?

It seem to me as I had not the permissions to create a new branch.

**Comment by UEWiebelitz** [comment]
OK, I think I got it. I submitted a PR.
