### ISSUE TITLE
rpdb folder not installed when using pip

### ISSUE THREAD

**Issue by domingoO-jones** [bluebird75/winpdb#36]
Hi,

the rpdb folder with the different scripts was not installed when i used pip to install the new 2.0.0.0 version so i got the following error:
`Traceback (most recent call last):
  File "winpdb.py", line 26, in <module>
    import rpdb.const
ModuleNotFoundError: No module named 'rpdb'`

after manually downloading the folder from here and putting it into the site-packages folder it works normally.

Thanks for the great work!

**Comment by bluebird75** [comment]
This was a packaging mistake. It should be fixed if you upgrade to the latest winpdb. Please run:

    pip install --upgrade winpdb
