### ISSUE TITLE
Pypi winpdb 1.4.8

### ISSUE THREAD

**Issue by Blanen** [bluebird75/winpdb#6]
If you try to install pypi with 

`pip install winpdb`

You get version 1.3.8. This version has never worked for me with rpdb2. I have to install 1.4.8 manually.

Looking at your pypi page: https://pypi.python.org/pypi/winpdb

It looks it has 1.4.8 but the actual download link links to http://winpdb.googlecode.com/files/winpdb-1.4.8.tar.gz Which 404s. 

It seems like it should point to http://code.google.com/p/winpdb/downloads/detail?name=winpdb-1.4.8.tar.gz&can=1&q=

**Comment by bluebird75** [comment]
I am not the official winpdb maintainer, just a friendly fork. I'll notify it to Nir Aides.

**Comment by bluebird75** [comment]
@nir , do you think you could do something ?

**Comment by bluebird75** [comment]
I have asked without success to become owner of the PyPI package.

In the meantime, I am working on relasing this fork under "Winpdb Reborn", with full support of WxPython 4.x (aka Phoenix).

Feel free to help, we are struggling on a few GUI issues before it can be released.

**Comment by skorokithakis** [comment]
The instructions say to install `winpdb-reborn`, but that package doesn't exist. Would you like to at least register the name?

**Comment by bluebird75** [comment]
I did just that. There is now a package of winpdb-reborn for Python 2.6 and 2.7 which you can install with pip. This is the stable version.

I will also add the Python 3 / WxWidgets 4 experimental version soon.

**Comment by bluebird75** [comment]
There is now also a package with Python 3. However, it is not stable yet.
