### ISSUE TITLE
Could not install winpdb-reborn using pip

### ISSUE THREAD

**Issue by KenzK** [bluebird75/winpdb#9]
Tried to install winpdb using "python -m pip install winpdb-reborn" but it gives and error message(see below for message)

>>>
_python -m pip install winpdb-reborn
Collecting winpdb-reborn
  Could not find a version that satisfies the requirement winpdb-reborn (from versions: )
No matching distribution found for winpdb-reborn_
<<<

**Comment by bluebird75** [comment]
Indeed, winpdb-reborn is not yet released. If you want to try it, you can clone this repository. Beware that it depends on WxPython pheonix which is still in beta, and that the GUI is not working yet ...
